"""Remove password_hash

Revision ID: 54da20113802
Revises: 3c79b959e7e0
Create Date: 2024-10-24 16:25:53.361784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54da20113802'
down_revision: Union[str, None] = '3c79b959e7e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
