"""Add card balance

Revision ID: bfbb28406e60
Revises: aa9aef82477f
Create Date: 2024-10-24 18:42:15.176692

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bfbb28406e60"
down_revision: Union[str, None] = "aa9aef82477f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Установка значения по умолчанию для существующих записей
    op.add_column(
        "cards", sa.Column("balance", sa.Float(), nullable=False, server_default="0.0")
    )
    # Удаление значения по умолчанию, чтобы в дальнейшем его не было
    op.alter_column("cards", "balance", server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cards", "balance")
    # ### end Alembic commands ###
